Spawn voxels based on weights
tictactoe-gamedev/tictactoe pull request #15
Opened 2023-12-30 16:02 UTC by hukasu

2024-01-07 12:56 UTC, kmlkcl requested changes
I just put a few points  I'm curious. Good job Sir!

2024-01-07 12:56 UTC, kmlkcl commented on src/config/world_configuration.rs
> +}
seems like we can use some positive size for one thing and use it like y = 20 then we'll know its -20 , 20 so it'll become a little cleaner

2024-01-07 12:56 UTC, kmlkcl commented on src/config/world_configuration.rs
> +}
if we use only positive values that would become *2

2024-01-07 12:56 UTC, kmlkcl commented on src/config/world_configuration.rs
> +}
same. lets use only positives to get rid of more lines

2024-01-07 12:56 UTC, kmlkcl commented on src/voxel/resource/voxel_adjacency.rs
> +}
well design sir

2024-01-07 12:56 UTC, kmlkcl commented on src/voxel/systems/spawn_voxel.rs
> +        let max_height = system_param.world_config.y_max - system_param.world_config.y_min;
again we can get rid of them in a cleaner way if we use positive only approach

2024-01-07 12:56 UTC, kmlkcl commented on src/voxel/systems/spawn_voxel.rs
> +                    });
my gut feeling says something is inefficient here. is it? my suspect comes from line 64 and so on

2024-01-07 12:56 UTC, kmlkcl commented on src/voxel/systems/spawn_voxel.rs
> +                            bevy::log::error!("Failed to cast usize index to u32.");
when this error happens? why?

2024-01-07 12:56 UTC, kmlkcl commented on src/voxel/systems/spawn_voxel.rs
> +                        bevy::log::error!("Failed to create weighted index distribution. '{err}'");
when this error happens? why?

2024-01-07 14:26 UTC, hukasu commented on src/voxel/systems/spawn_voxel.rs
> +                            bevy::log::error!("Failed to cast usize index to u32.");
On this code the likelyhood of happening is zero, as the return from `sample` which is a `usize` will never overflow the size of an `u32`

2024-01-07 14:28 UTC, hukasu commented on src/voxel/systems/spawn_voxel.rs
> +                    });
i don't have a hierarchical data structure at this point, so i just iterate over all voxels linearly, take the ones that are adjacent and do the weight multiplication

2024-01-07 14:31 UTC, hukasu commented on src/config/world_configuration.rs
> +}
i'm using like this at this moment because i had then not necessarily being symetric (i.e. -5, 20)

2024-01-07 14:33 UTC, hukasu commented on src/voxel/systems/spawn_voxel.rs
> +                        bevy::log::error!("Failed to create weighted index distribution. '{err}'");
the constructor of WeightedIndex may fail if the iterator is empty or if there is any weight smaller than zero.
https://rust-random.github.io/rand/rand/distributions/struct.WeightedIndex.html#method.new

2024-01-08 12:21 UTC, kmlkcl commented on src/voxel/systems/spawn_voxel.rs
> +                    });
so this part is a bit performance killer. Even you won't change it, adding a //TODO: around would be nice for future

2024-01-08 12:21 UTC, kmlkcl commented on src/voxel/systems/spawn_voxel.rs
> +                            bevy::log::error!("Failed to cast usize index to u32.");
lets remove it then :smile:

2024-01-08 12:25 UTC, kmlkcl requested changes
one more turn and I'll approve even there's no change :+1: just wanted to share a few points

2024-01-08 12:25 UTC, hukasu commented on src/voxel/systems/spawn_voxel.rs
> +                            bevy::log::error!("Failed to cast usize index to u32.");
It is like this because Rust requires that every error is treated at every level, you can't let a "throw" just go over to be treated at a upper level, either you treat it or explicitly re-throw

2024-01-18 19:34 UTC, merged