Quest 2.1 Bevy
tictactoe-gamedev/tictactoe pull request #6
Opened 2023-12-19 13:06 UTC by hukasu

Code for the Quests 2 and 2.1 done using the [Bevy Engine](https://bevyengine.org/).

2023-12-19 15:58 UTC, kmlkcl requested changes
so far so good. Just a few minor points and questions about rust & bevy!we should probably move this project as a reference for bevy on somewhere that everyone can use. what do you think?

2023-12-19 15:58 UTC, kmlkcl commented on src/voxel/component.rs
> +    voxel_type: u64,
is there a specific reason for using u64 here?

2023-12-19 15:58 UTC, kmlkcl commented on README.md
thank you sir! :) I think we should add bevy to our main as the third option and this one can be a good reference project

2023-12-19 15:58 UTC, kmlkcl commented on src/voxel/mod.rs
> +        let x = ((entropy.next_u32() % (world_config.x_min.abs_diff(world_config.x_max + 1)))
is there a reason to use abs_diff here? isn't max guaranteed to be greater than min at any point?

2023-12-19 15:58 UTC, kmlkcl commented on src/voxel/mod.rs
> +                * world_config.z_min.abs_diff(world_config.z_max + 1),
I'd simplify them with a method in world_config like world_x_length world_z_length. why? because it seems its used a few other places. so writing it with a less 'dirty' function call would be better

2023-12-19 15:58 UTC, kmlkcl commented on src/voxel/mod.rs
> +        } else {
I didn't understand the syntax sphagetti here. What's happening there? when this part is called? It seems like a third case for the if else but without else keyword. Is it because I'm not familiar with the syntax or is it just dirty nasty code?

2023-12-21 12:57 UTC, hukasu commented on src/main.rs
> +    let voxel_type = entropy.next_u64() % 4;
I just default to using 64 bits, i don't think that on this ocasion there would be any difference, if i were mixing 64bit, 32bits, 16bit, and 8bits variables into the struct, there would be some padding on the layout

2023-12-21 12:59 UTC, hukasu commented on src/main.rs
> +                    z: z as f32,
all casts in rust must be explicit, and the Vec3 struct takes 3 f32, i could store the x and z as i32 in a different component, but for know i'm just using it to construct the Transform Component

2023-12-21 13:01 UTC, hukasu commented on src/main.rs
> +    let mesh = asset_server.load("cube.gltf#Mesh0/Primitive0");
you somehow commented on a older version of the main.rs, on the current version the calculation of x and z use the values in the WorldConfiguration resource
resources in Bevy are basicaly singletons
the file path remained as a magic value on the current version

2023-12-21 13:02 UTC, hukasu commented on README.md
Sure

2023-12-21 13:05 UTC, hukasu commented on src/voxel/mod.rs
> +        let x = ((entropy.next_u32() % (world_config.x_min.abs_diff(world_config.x_max + 1)))
abs_diff has a nicety of casting from i32 to u32
the way i did one of the tasks of Quest 2 is that you have a windows were you can edit the world_config values, and on change there might be a frame were the values can not be ordered, but i have a system registered on the ECS that every frame checks if the bounds are correct, or modifies the max_x or max_z to be min + 1

2023-12-21 13:12 UTC, hukasu commented on src/voxel/mod.rs
> +        } else {
that was just ugly code really, in rust every block returns a value, so you can have an if return a value to be used in a if
```rust
// Rust does not have trinary operations, but it has this
let x = 5;
let a = if x > 3 { "bigger than 3" } else { "smaller or equal to 3" );
```
the `a` variable has a string after this snippet runs

on the code it self i'm using an if as the condition to another, `if (if .. {..} else {..}) {..} else {..}`

2023-12-21 13:18 UTC, kmlkcl commented on src/main.rs
> +    let mesh = asset_server.load("cube.gltf#Mesh0/Primitive0");
Yeah yeah I remember that :))

2023-12-21 13:21 UTC, kmlkcl commented on src/voxel/component.rs
> +    voxel_type: u64,
out of curiosity isn't padding done by compiler?  assume you needed to add another 32 bit value to this struct, or run this code in an 32 bit architecture. isn't that a scenario where things will get worse? is this a common practice with Rust or, a "well..whatever" case on your end ?

2023-12-21 13:24 UTC, kmlkcl commented on src/voxel/mod.rs
> +        } else {
well, then I'd suggest a cleaner syntax here.

2023-12-21 13:25 UTC, hukasu commented on src/voxel/component.rs
> +    voxel_type: u64,
currently it's a "well.. whatever" case, yes

but rust does not use the same memory layout as C, there is an attribute to for the same layout as C though
https://doc.rust-lang.org/reference/type-layout.html

2023-12-21 13:41 UTC, closed without merging